name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # 确保您使用的是正确的分支名，通常是 main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install spaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Run Streamlit app
        run: |
          streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501
